### ISSUE TITLE
Include JSON data in build

### ISSUE THREAD

**Issue by mrchucho** [mdx-dev/platform-ui-pdf-generator#3]
Attempting to build the app for serving (via nginx), I encountered two issues.

1. ```gulp build``` or ```gulp optimize``` doesn't include the JSON data (medicare_pdf_big.json) in the resulting ```build``` directory. This contents of this directory are what would be used to serve the app (similar to what we're doing with platform-ui).
2. The PDF service attempts to access the JSON data from ```app/json/medicare_pdf_big.json```, which is not an usable URL **when serving the app from the build directory**.

I believe 1. can be resolved by updating or adding a task to the gulp file. Also, can @natemcdowel or @sonicparke confirm that ```gulp build``` is what should be used for a "production" build?

I assume 2. can be resolved by adjusting the URL accessed by the PDF service. Either making it relative or the root directory.

**Comment by mrchucho** [comment]
Another option would be to make the location of the JSON data a configuration option or parameter. Then put the JSON data in that location by some other means.

**Comment by natemcdowel** [comment]
@mrchucho This will be broken down by client and by state. Let me talk to @yitznewton about which of these options we'd like to pursue for plugging in the provider JSON file:

1. it can be generated however & maintained in the ui-pdf-gen repo (like now)
2. it should be an endpoint in the API (disregarding current time / performance issues)
3. it could be generated however & uploaded to some URL (e.g. on S3)

**Comment by mrchucho** [comment]
Sounds good, @natemcdowel. I think it would be helpful to make this an option / parameter and update the PDF service accordingly. Then the app will work regardless of the final decision.

**Comment by robincurry** [comment]
a 4th option to consider, would be a hybrid of 2 and 3. It could be a generated/static api endpoint (rather than uploaded to S3). not sure, myself, but just a thought.

**Comment by mrchucho** [comment]
@robincurry yeah, my only thought was that it's really easy to generate a file then upload it to **one** place and have all the apps "serve" it. And by serve, I mean redirect those requests to S3. Versus generating a file and making sure it ends up on all the client environment's web servers. This is exactly what we do with the existing PDFs now.

**Comment by sonicparke** [comment]
@mrchucho @natemcdowel Got gulp json data copying to build folder in PR https://github.com/mdx-dev/platform-ui-pdf-generator/pull/4

**Comment by mrchucho** [comment]
Did we get this resolved? I believe we did. @sonicparke or @natemcdowel can you confirm & close this issue?

**Comment by sonicparke** [comment]
Resolved
